config:
    orderFrequencyMs: 12000
    names: [
        Erica,
        Susan,
        Ava,
        Lola,
        Estaban,
        Hans,
        Vienna,
        Josephine,
        Hugo,
        Huw,
        Rian,
        Yangyang,
        Bowen,
        Gen,
        Misty,
        Yolanda,
        Fran,
        Bea,
        Tay,
        McKenzie,
        Polly,
        Siobhan,
        Rohan,
        Mike,
        Soph,
        Zoë,
    ]
    items: 
        entree:
            - Kiss (3 serves)
            - Twink
            - Trio of dips 
            - Assortment of participation medals
            - Glass brick
            - A dozen oysters
        main:
            - Wired headphones
            - Insurmountable feeling of guilt
            - Cottees cordial (undiluted)
            - Unsuccessful Hinge date
            - Hot chips
            - Hardcover edition of War and Peace
        dessert:
            - Tiramisu 
            - A good cry
            - Party mix (bananas only)
            - Nang
            - MILF or DILF depending on what's in season
            - Fredo icecream cake (hot)
        drinks:
            - Milk (source undisclosed) 
            - Goon bag 
            - Unfiltered Yarra river water
            - Your mums tears
            - Exhaust fumes
            - Negroni



