config:
    orderFrequencyMs: 10000
    names: [
        Erica,
        Susan,
        Ava,
        Lola,
        Estaban,
        Hans,
        Vienna,
        Josephine,
        Hugo,
        Huw,
        Rian,
        Yangyang,
        Bowen,
        Gen,
        Misty,
        Yolanda,
        Fran,
        Bea,
        Tay,
        McKenzie,
        Polly,
        Siobhan,
        Rohan,
        Mike,
        Soph,
        Zoë,
    ]
    items: 
        entree:
            - name: Kiss (3 serves)
              description:
                Artisanal kiss served warm, with included reach-around
              price: 12
              addons:
                - price: 20
                  description: "With a bit of tongue :P"
                  name: "Tongue"
            - name: Twink
              price: 12
              description: ""
              addons:
                - price: 20
                  description: "With a bit of tongue :P"
                  name: "Tongue"
            - name: Trio of dips 
              price: 12
              description: ""
            - name: Assortment of participation medals
              price: 12
              description: ""
            - name: Glass brick
              price: 12
              description: ""
            - name: A dozen oysters
              price: 12
              description: ""
        main:
            - name: Wired headphones
              price: 1
              description: ""
            - name: Insurmountable feeling of guilt
              price: 1
              description: ""
            - name: Cottees cordial (undiluted)
              price: 1
              description: ""
            - name: Unsuccessful Hinge date
              price: 1
              description: ""
            - name: Hot chips
              price: 1
              description: ""
            - name: Hardcover edition of War and Peace
              price: 1
              description: ""
        dessert:
            - name: Tiramisu 
              price: 1
              description: ""
            - name: A good cry
              price: 1
              description: ""
            - name: Party mix (bananas only)
              price: 1
              description: ""
            - name: Nang
              price: 1
              description: ""
            - name: MILF or DILF depending on what's in season
              price: 1
              description: ""
            - name: Fredo icecream cake (hot)
              price: 1
              description: ""
        drinks:
            - name: Milk (source undisclosed) 
              price: 1
              description: ""
            - name: Goon bag 
              price: 1
              description: ""
            - name: Unfiltered Yarra river water
              price: 1
              description: ""
            - name: Your mums tears
              price: 1
              description: ""
            - name: Exhaust fumes
              price: 1
              description: ""
            - name: Negroni
              price: 1
              description: ""



